config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/about', to: 'homes#about'
  resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy]do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'timeline'

  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
  
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  
  validates :title, presence: true
  validates :image, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  default_scope -> { order(created_at: :desc) }
  validates :introduction, presence: false, length: { maximum: 50 } # 自己紹介の最高文字数は50文字
  
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  # フォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
# フォローを外す
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
# 引数に渡したユーザをフォローしている（true）
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    post_images_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: @post_image.id)
    favorite.save
    # redirect_to post_image_path(post_image)
  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: @post_image.id)
    favorite.destroy
    # redirect_to post_image_path(post_image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    PostComment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end
  
  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]
  def new
    @post_image = PostImage.new
  end

  # 投稿データの保存
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
     if @post_image.save
      redirect_to post_images_path
     else
      render :new
     end
  end

  def index
    @post_images = PostImage.all
    # @post_images = PostImage.page(params[:page]).reverse_order
    @q = PostImage.ransack(params[:q])
    @post_images = @q.result(distinct: true)
  end

  def show
    # @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    # @post_image = PostImage.find(params[:id])
  end

  def update
    # @post_image = PostImage.find(params[:id])
    @post_image.update(post_image_params)
    redirect_to post_image_path(@post_image.id)
  end

  def destroy
    # @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end
  
  # def set_search
  #   if log_in?
  #     @search_word = params[:q][:title_cont] if params[:q]
  #     @q = current_user.feed.page(params[:page]).per(10).ransack(params[:q])
  #     @feed_items = current_user.feed.page(params[:page]).per(10)
  #     @posts = @q.result(distinct: true)
  #   end
  # end

  # 投稿データのストロングパラメータ
  private
  # 別メソッドとして定義
  def set_post_image
    @post_image = PostImage.find(params[:id])
  end

  def post_image_params
    params.require(:post_image).permit(:title, :image, :caption)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  # followings, followersは省略
    
  def followings
     user = User.find(params[:user_id])
     @users = user.followings
  end

  def followers
     user = User.find(params[:user_id])
     @users = user.followers
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @post_image = PostImage.new
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end
  
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images
    # .page(params[:page]).reverse_order
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  def timeline
    @user = current_user
    # @users = @user.following_user
    # follows_ids = @user.following_user.pluck(:id)  # フォローしている人のIDだけを取り出す
    # follows_ids.push(@user.id)                       # フォローしている人のID配列に自分のIDも追加
    # @post_images = PostImage.where(user_id: follows_ids).page(params[:page]).reverse_order
  end
  
   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if @post_image.favorited_by?(current_user) %>
  <span>
    <%= link_to post_image_favorites_path(@post_image), class:"text-dark", method: :delete, remote: true do %>
      <i class="fas fa-heart" style="color: #E03D58;"></i> <%= @post_image.favorites.count %>
    <% end %>
  </span>
<% else %>
  <span>
    <%= link_to post_image_favorites_path(@post_image), class:"text-dark", method: :post, remote: true do %>
      <i class="far fa-heart" style="color: #F5569C;"></i> <%= @post_image.favorites.count %>
    <% end %>
  </span>
<% end %>
  

app/views/favorites/create.js.erb
$("#favorite-<%= @post_image.id %>").html("<%= j(render partial: 'favorites/favorite-btn', locals: { post_image: @post_image }) %>");

app/views/favorites/destroy.js.erb
$("#favorite-<%= @post_image.id %>").html("<%= j(render partial: 'favorites/favorite-btn', locals: { post_image: @post_image }) %>");

app/views/homes/about.html.erb
<div class="about">
  <div class="about-visual-content">
    <p class="about-visual-text">
      Here you can share<br>
      your impressions of <br>
      the spots you visited
    </p>
  </div>

  <div class="d-flex justify-content-center">
    <div class="about-image scrollanime"><%= image_tag 'about2.jpg' %></div>
    <div class="about-text scrollanime">
      <strong>
        Feel free to post <br>
        your impressions of the trip.
      </strong><br><br>
      あなたの訪れたスポットを自由に投稿し、<br>
      多くの人と共有しましょう
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <div class="about-text scrollanime">
      <strong>Let's "favorite".</strong><br><br>
      共感したものには「いいね」ができます
    </div>
    <div class="about-image scrollanime"><%= image_tag 'about3.jpg' %></div>
  </div>
  <div class="d-flex  justify-content-center">
    <div class="about-image scrollanime"><%= image_tag 'about4.jpg' %></div>
    <div class="about-text scrollanime">
      <strong>Let's "follow".</strong><br><br>
      気になるユーザーはフォローすることができます
    </div>
  </div>
  <div class="d-md-flex justify-content-center">
    <div class="about-form">
      <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-dark' %>
    </div>
    <div class="about-form">
      <%= link_to "Log in", new_user_session_path, class: 'nav-link text-dark' %>
    </div>
  </div>
  <body>
      <%= yield %>
      <span id="back">
        <a href="">
          <%= image_tag asset_path('arrow.png'), data: {"turbolinks"=>false}, class: "arrow" %>
        </a>
      </span>
    </body>
</div>

app/views/homes/top.html.erb
 <div id="container">
      <div id="theTarget">
        <div class="image1"></div>
        <div class="image2"></div>
        <div class="image3"></div>
        <div class="image4"></div>
        <div class="image5"></div>
      </div>
    </div>

    <div class="top-visual-content">
    <p class="top-visual-text">
      Welcome to <strong>My Trip Life</strong>
      <i class="fas fa-suitcase-rolling fa-spin"></i><br>
      Let's enjoy your trip life .
    </p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrippersApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand" href="/" data-turbolinks="false"><%= image_tag('horizontal.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <!--ユーザーがサインインしている時-->
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Let's post", user_timeline_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'All post', post_images_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'My page', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to ' Users',users_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <!--ユーザーがログアウトしている時-->
            <li class="nav-item">
              <%= link_to "HOME", root_path, data: {"turbolinks" => false}, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <p class="footer-text">©2021 Trippers_App All Rights Reserved.</p>
    </footer>
          
  </body>
</html>

app/views/post_comments/_form.html.erb
<%= form_with(model:[@post_image, @post_comment]) do |f| %>
    <%= f.text_area :comment, cols:'48', rows:'5', class: "input-mysize" %><br>
    <%= f.submit "Create Comment", class: "btn btn-outline-darl comment-submit float-right" %>
<% end %>

app/views/post_comments/_index.html.erb
<!--コメント内容２件-->
<%= @post_image.post_comments.count %> comments <i class="far fa-comments"></i>
  <% if @post_image.post_comments.count > 2 %>
    <a class="more" data-toggle="collapse" href="#comment" aria-expanded="false" aria-controls="comment">more...</a>
  <% end %>

  <% @post_image.post_comments.first(2).each do |post_comment| %>
    <% unless post_comment.id.nil? %>
    <div class="comment-container">
      <div class="comment-box">
        <div class="comment-avatar">

          <%= attachment_image_tag post_comment.user, :profile_image, fallback: "no_image.jpg", class:"comment-image rounded-circle", size: "40x40" %>
             </div>
             <div class="comment-text">
              <p><%= link_to "by#{post_comment.user.name}", user_path(post_comment.user.id), class:"text-muted" %></p>
              <div class="comment-entry">
              <%= post_comment.comment %>

            </div>
            <span><i class="fa fa-calendar"></i> <%= post_comment.created_at.strftime('%Y/%m/%d') %> ｜ </span>
            <% if post_comment.user == current_user %>
                <i class="fas fa-trash" style="color: black;"></i>
                <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete, class: "comment_destroy text-dark" %>
              <% end %>
              <% end %>
          </div>
          </div>
          </div>
        <% end %>


  <!--コメント内容３件目以降-->
  <div class="collapse" id="comment">
  <% @post_image.post_comments.offset(2).each do |post_comment| %>
    <% unless post_comment.id.nil? %>
      <div class="comment-container">
        <div class="comment-box">
          <div class="comment-avatar">
            <%= attachment_image_tag post_comment.user, :profile_image, fallback: "no_image.jpg", class:"comment-image rounded-circle", size: "40x40" %>
       </div>
            <div class="comment-text">
              <p><%= link_to "by#{post_comment.user.name}", user_path(post_comment.user.id), class:"text-muted" %></p>
              <div class="comment-entry">
              <%= post_comment.comment %>
            </div>
            <span><i class="fa fa-calendar"></i> <%= post_comment.created_at.strftime('%Y/%m/%d') %> ｜ </span>
            <% if post_comment.user == current_user %>
                <i class="fas fa-trash" style="color: black;"></i>
                <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete, class: "comment_destroy text-dark" %>
              <% end %>
              <% end %>
              </div>
          </div>

        <% end %>
      </div>

app/views/post_images/_index.html.erb
<div class="d-lg-flex d-md-flex my-box-light flex-wrap mt-3">
  <% post_images.each do |post| %>
    <div class="my-box-post col-sm-4">
      <%= link_to post_image_path(post_image) do %>
      <div class="index mt-3 mb-3">
        <%= attachment_image_tag post_image, :image, :fill, 200, 200, format: 'jpeg', fallback: "unnamed.jpg", size:'200x200' %>
        <p><%= post_image.title %></p>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/post_images/_list.html.erb
<div class="d-lg-flex d-md-flex my-box-light flex-wrap mt-3">
  <% post_images.each do |post_image| %>
  <div class="my-box-post col-sm-4">
    <%= link_to post_image_path(post_image.id) do %>
      <%= attachment_image_tag post_image, :image, :fill, 200, 200, format: 'jpeg', fallback: "unnamed.jpg", size:'200x200' %>
    <% end %>
    <div class="index mt-3 mb-3">
      <div class="row">
        <div class="col-2">
          <%#= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.title %></span></strong>
            <% end %>
          </p>
          </div>
      </div>
    </div>
  </div>
  <% end %>
  <%#= paginate post_images %>
</div>

app/views/post_images/edit.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">Post editting</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <%= @post_image.errors.count %>件のエラーが発生しました
          <% @post_image.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @post_image, local:true do |f| %>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :title, class:"form-control", placeholder:"旅行のタイトル" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"旅行のおすすめポイントを紹介しよう" %>
          <hr>
          <%= f.submit 'Update', class:"btn btn-light btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
          

app/views/post_images/index.html.erb
<div class="container">
  <h3 class="mt-10">All posts</h3>
      <%= search_form_for @q do |f| %>
        <%#= f.label :title, "Keyword" %>
        <%= f.search_field :title_cont, placeholder:"Search" %>

        <%= f.submit "検索" %>
      <% end %>
    <div class="text-right">
      <%= link_to new_post_image_path do %>
      <i class="fas fa-pencil-alt p-3 rounded-circle  shadow rounded bg-light" style="color: grey;"></i>
    <% end %>
    </div>
</div>

      <body>
            <%= yield %>
            <span id="back">
              <a href="">
                <%= image_tag asset_path('arrow.png'), data: {"turbolinks"=>false}, class: "arrow" %>
              </a>
            </span>
      </body>
      </div>
    </div>
  </div>
    <%= render 'post_images/list', post_images: @post_images %>

app/views/post_images/new.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h4 class="text-dark bg-light p-4 mb-0">new post</h4>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <%= @post_image.errors.count %>件のエラーが発生しました
          <% @post_image.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @post_image, local:true do |f| %>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :title, class:"form-control", placeholder:"旅行のタイトル" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"旅行のおすすめポイントを紹介しよう" %>
          <hr>
          <%= f.submit 'Create post', class:"btn btn-light btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row justify-content-md-center">
    <div class="col-lg-6 offset-col-xs-12">
      <div class="post-body">
          <%= attachment_image_tag @post_image, :image, :fill, 200, 200, format: 'jpeg', fallback: "unnamed.jpg", size:'200x200' %>


      </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(@post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= @post_image.title %></span></strong>
            <% end %>
          </p>
            <p class="card-title">説明：<%= @post_image.caption %></p>

            <p><%= link_to "by#{@post_image.user.name}", user_path(@post_image.user.id), class:"text-muted" %></p>
            <!--<span><i class="fas fa-user"></i> By <%#= @post_image.user.name %> ｜ </span>-->
            <span><i class="fa fa-calendar"></i> <%= @post_image.created_at.strftime('%Y/%m/%d') %> ｜ </span>
            <!--<span><i class="fa fa-comment"></i> <%#= link_to "#{@post_image.post_comments.count}", post_image_path(@post_image.id), class:"text-dark" %> ｜ </span>-->

            <span id="favorite-<%= @post_image.id %>">
              <%= render partial: "favorites/favorite-btn", locals: { post_image: @post_image } %>
            </span>

                <% if @post_image.user == current_user %>
                  <span> ｜ </span>
                  <%= link_to "編集", edit_post_image_path(@post_image), class:"text-dark" %>
                  <%= link_to "削除", post_image_path(@post_image), class:"text-dark", method: :delete %>
                <% end %>
              </div>
            </div>

        <div class="col-lg-6 offset-col-xs-12">
        <ul>
          <li id="comments_area">
            <%= render 'post_comments/index', post_comments: @post_comments %>
          </li>
        </ul>

        <div class="comment_create">
          <%= render 'post_comments/form', post_comments: @post_comments %>
        </div>

    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<div class="container">
  <div class="row no-gutters">
    <h3 class="col-12 col-sm col-md-8 mt-5">Follower users</h3>
      <% if @users.exists? %>
        <%= render '/users/index', users: @users %>
      <% else %>
    <div class="col-12">
      <p>No users</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th>follows</th>
      <th>followers</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class:'rounded-circle' %>
          <% end %>
          </td>
        <td>
          <%= link_to user_path(user), class:"text-dark" do %>
            <%= user.name %>
          <% end %>
          </td>
        <td><%= user.followings.count %></td>
        <td><%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "unfollow", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-secondary" %>
            <% else %>
              <%= link_to "follow", user_relationships_path(user.id), method: :post, class: "btn btn-outline-primary" %>
            <% end %>
          <% end %>
        </td>
        
      </tr>
    <% end %>

  </tbody>
</table>

app/views/users/show.html.erb
<div class="container mt-5 mb-5">
  <div class="profile-container">
    <h3 class="profile-name"><%= @user.name %></h3>
    <%= attachment_image_tag @user, :profile_image, :fill, 250, 250, fallback: "no_image.jpg", size:'100x100', class:'rounded-circle' %><br>
    <p><%= @user.introduction %></p>
      <div class="mypage-form-follow">

        <%= link_to user_followings_path(@user), class:"btn btn-light" do %>
        <%= @user.followings.count %>follows<i class="fas fa-user-friends"></i>
        <% end %>
      </div>

      <div class="mypage-form-follow">

        <%= link_to user_followers_path(@user), class:"btn btn-light" do %>
        <%= @user.followers.count %>followers<i class="fas fa-user-friends"></i>
        <% end %>

        <% if current_user != @user %>
          <% if current_user.following?(@user) %>
            <%= link_to "unfollow", user_relationships_path(@user.id), method: :delete, class: "btn btn-outline-secondary" %>
          <% else %>
            <%= link_to "follow", user_relationships_path(@user.id), method: :post, class: "btn btn-outline-primary" %>
          <% end %>
        <% else %>
      <div class="mypage-form">
          <%= link_to edit_user_path(@user), class:"btn btn-light" do %>
          profile editing<i class="fas fa-user-edit"></i>
          <% end %>
        <% end %>

    <body>
      <%= yield %>
      <span id="back">
        <a href="">
          <%= image_tag asset_path('arrow.png'), data: {"turbolinks"=>false}, class: "arrow" %>
        </a>
      </span>
    </body>
  </div>
</div>
    <%= render 'post_images/list', post_images: @post_images %>
    <%#= paginate @post_images %>

app/views/users/timeline.html.erb
<div class="container">
  <h3 class="col-12 col-sm col-md-8 mt-5">Let's post</h3>
  <div class="text-center">
  <!--  <%#= link_to new_post_image_path do %>-->
  <!--    <i class="fas fa-pencil-alt p-3 rounded-circle  shadow rounded bg-light" style="color: grey;"></i>-->
  <!--  <%# end %>-->
  <!--</div>-->

  <!--<#% if @users.count > 0 %>-->
  <!--  <%#= render 'post_images/index', post_images: @post_images %>-->
  <!--<#% elsif @post_images.count > 0 %>-->
  <!--  <%#= render 'post_images/index', post_images: @post_images %>-->
  <!--<#% else %>-->
    <p class="mx-auto" style="width: 90%;">Share your photos!</p>
    <p class="mx-auto" style="width: 90%;">Let's follow users!</p>
    <p class="mx-auto" style="width: 90%;">Let's get started!!<i class="fas fa-plane fa-spin"></i></p>
    
    <%= link_to new_post_image_path do %>
      <i class="fas fa-pencil-alt p-3 rounded-circle  shadow rounded bg-light" style="color: grey;"></i>
    <% end %>
  <%# end %>
</div>